spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/rhcontroldocuments?createDatabaseIfNotExist=true'
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:29092
server:
  port: '9090'
aws:
  acessKey: '${ACESS_KEY}'
  secretKey: '${SECRET_KEY}'



